import { useEffect, useState } from "react";
import {
  collection,
  limit,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";

import { db } from "../firebase";

export default function PredictionHistory() {
  const [predictions, setPredictions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    const predictionsQuery = query(
      collection(db, "aiPredictions"),
      orderBy("createdAt", "desc"),
      limit(10)
    );

    const unsubscribe = onSnapshot(
      predictionsQuery,
      (snapshot) => {
        const predictionData = snapshot.docs.map((document) => ({
          id: document.id,
          ...document.data(),
        }));

        setPredictions(predictionData);
        setLoading(false);
        setErrorMessage("");
      },
      (error) => {
        console.error("Prediction history error:", error);

        setErrorMessage(
          "Unable to load AI prediction history."
        );

        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, []);

  const formatDate = (timestamp) => {
    if (!timestamp?.toDate) {
      return "Just now";
    }

    return timestamp.toDate().toLocaleString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const getRiskStyle = (riskLevel) => {
    if (riskLevel === "Critical Risk") {
      return "border-red-500/30 bg-red-500/10 text-red-300";
    }

    if (riskLevel === "High Risk") {
      return "border-orange-500/30 bg-orange-500/10 text-orange-300";
    }

    if (riskLevel === "Medium Risk") {
      return "border-amber-500/30 bg-amber-500/10 text-amber-300";
    }

    return "border-emerald-500/30 bg-emerald-500/10 text-emerald-300";
  };

  return (
    <section className="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">
      <div className="flex flex-col justify-between gap-3 border-b border-slate-800 px-6 py-5 sm:flex-row sm:items-center">
        <div>
          <p className="text-sm font-semibold uppercase tracking-wider text-violet-400">
            AI Analysis Records
          </p>

          <h2 className="mt-1 text-2xl font-bold text-white">
            Prediction History
          </h2>

          <p className="mt-1 text-sm text-slate-400">
            Latest pollution predictions generated by AquaGuard AI.
          </p>
        </div>

        <div className="rounded-lg border border-slate-700 bg-slate-800 px-4 py-2 text-sm text-slate-300">
          Latest {predictions.length} predictions
        </div>
      </div>

      {loading && (
        <div className="px-6 py-12 text-center">
          <div className="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-slate-700 border-t-violet-400" />

          <p className="mt-4 text-sm text-slate-400">
            Loading prediction history...
          </p>
        </div>
      )}

      {!loading && errorMessage && (
        <div className="m-6 rounded-xl border border-red-500/30 bg-red-500/10 p-5 text-red-300">
          {errorMessage}
        </div>
      )}

      {!loading &&
        !errorMessage &&
        predictions.length === 0 && (
          <div className="px-6 py-14 text-center">
            <div className="text-5xl">🤖</div>

            <h3 className="mt-4 text-lg font-semibold text-white">
              No AI predictions found
            </h3>

            <p className="mt-2 text-sm text-slate-400">
              Generate a prediction to see it here.
            </p>
          </div>
        )}

      {!loading &&
        !errorMessage &&
        predictions.length > 0 && (
          <div className="overflow-x-auto">
            <table className="min-w-full">
              <thead className="bg-slate-950/60">
                <tr className="text-left text-xs uppercase tracking-wider text-slate-400">
                  <th className="px-6 py-4 font-semibold">
                    Parameters
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Industrial Activity
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Risk Score
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Risk Level
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Generated By
                  </th>

                  <th className="px-6 py-4 font-semibold">
                    Date
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-slate-800">
                {predictions.map((prediction) => (
                  <tr
                    key={prediction.id}
                    className="transition hover:bg-slate-800/40"
                  >
                    <td className="whitespace-nowrap px-6 py-4">
                      <div className="text-sm text-slate-300">
                        pH:{" "}
                        <span className="font-semibold text-white">
                          {prediction.ph}
                        </span>
                      </div>

                      <div className="mt-1 text-xs text-slate-500">
                        Turbidity: {prediction.turbidity} NTU
                      </div>

                      <div className="mt-1 text-xs text-slate-500">
                        DO: {prediction.dissolvedOxygen} mg/L
                      </div>

                      <div className="mt-1 text-xs text-slate-500">
                        Rainfall: {prediction.rainfall} mm
                      </div>
                    </td>

                    <td className="whitespace-nowrap px-6 py-4 text-sm text-slate-300">
                      {prediction.industrialActivity ||
                        "Not specified"}
                    </td>

                    <td className="whitespace-nowrap px-6 py-4">
                      <span className="text-2xl font-bold text-white">
                        {prediction.riskScore ?? 0}
                      </span>

                      <span className="text-sm text-slate-500">
                        /100
                      </span>
                    </td>

                    <td className="whitespace-nowrap px-6 py-4">
                      <span
                        className={`rounded-full border px-3 py-1 text-xs font-semibold ${getRiskStyle(
                          prediction.riskLevel
                        )}`}
                      >
                        {prediction.riskLevel || "Unknown"}
                      </span>
                    </td>

                    <td className="px-6 py-4 text-sm text-slate-400">
                      {prediction.userEmail || "Unknown user"}
                    </td>

                    <td className="whitespace-nowrap px-6 py-4 text-sm text-slate-400">
                      {formatDate(prediction.createdAt)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
    </section>
  );
}